baseURL = "https://kryzp.github.io/"
languageCode = "en-us"
title = "428 Magpies"

pagination.pageSize = 5
summaryLength = 0

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['$', '$']]

[markup.highlight]
  noClasses = false

[params]
  math = true
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  #readingTime = true

[languages]
  [languages.en]
    languageName = "English"
    title = "428 Magpies"

    [languages.en.params]
      subtitle = "A blog mostly focused on random thoughts, computer graphics and physics related... stuff."
      owner = "Kry≈°tof Przeczek"
      keywords = ""
      copyright = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "428 Magpies"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about"
        [[languages.en.menu.main]]
          identifier = "projects"
          name = "Projects"
          url = "/projects"

[module]
  [[module.imports]]
    path = "github.com/panr/hugo-theme-terminal/v4"
